name: Update-box64

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-box64:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Install dependencies and build in dockerfile
        uses: docker://ubuntu:18.04
        with:
          entrypoint: "/bin/bash"
          args: /github/workspace/.github/workflows/install-dependencies-and-build.sh

      - name: Upload
        run: |
          if [[ -f exited_successfully.txt ]]; then
            rm exited_successfully.txt
            exit 0
          fi
          cd $GITHUB_WORKSPACE
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          bash -c "git add . && git commit -m 'Update box64 to commit $(cat commit.txt)'" || true
          git push
